name: climatedt_workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - ipykernel
  - jupyter
  - nbformat
  - healpy
  - gdal
  - eccodes
  - intake
  - intake-esm
  - cdo
  - pandas
  - xarray
  - gcsfs
  - zarr
  - cartopy
  - pip
  - spyder
  - pip:
      - lxml
      - conflator
      - earthkit-data==0.20.0
      - earthkit-regrid
      - earthkit-plots
      - earthkit-geo
      - covjsonkit>=0.2.5
      - polytope-client
      - kaleido
      - h3
