name: climatedt_workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - ipykernel
  - jupyter
  - nbformat
  - healpy
  - cartopy
  - fiona
  - pip:
      - lxml
      - conflator
      - earthkit-data==0.20.0
      - earthkit-regrid
      - earthkit-plots
      - earthkit-geo
      - covjsonkit
      - polytope-client
      - kaleido
      - h3
