channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - ipykernel
  - nbformat
  - healpy
  - pip
  - intake
  - intake-esm
  - pandas
  - xarray
  - gcsfs
  - zarr
  - cartopy
name: climatedt_workshop